### PR TITLE
test/api: add more tests for low-level API

### PR DESCRIPTION
**Pull request by nbaksalyar**
Including tests for serialisation, removal, and restoration of appendable data.

---
This change is [Reviewable](https://reviewable.io/reviews/maidsafe/safe_core/337)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @ustulation

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by ustulation** [comment]
Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/ffi/low_level_api/appendable_data.rs, line 890 at r2](https://reviewable.io:443/reviews/maidsafe/safe_core/337#-KRnwCrZCwTAH6eE3Fqp:-KRnwCrZCwTAH6eE3Fqq:b-73om4p) ([raw file](https://github.com/maidsafe/safe_core/blob/565b467b1f58a615025dcf21fd0ed06fdaaa1d9c/src/ffi/low_level_api/appendable_data.rs#L890)):*
> ```Rust
>             assert_eq!(num, 1);
>             assert_eq!(appendable_data_num_of_deleted_data(got_ad_h, &mut num), 0);
>             assert_eq!(num, 1);
> ```

Besides checking with `got_ad_h` as above (which asserts the local AppendableData is updated if the post was successful), fetching the data from the network again with GET and asserting the same conditions hold true for that too would be of added benefit as that would assert that network (hence mock-routing) is well behaved too.

Similarly in other places.

Of-course ,keep freeing handles which you no longer need such as either `got_ad_h` or `got_again_ad_h` or any other way you prefer (such as `appendable_data_free(got_ad_h) and now reuse it to get a new one after a fetch from network).

---

*[src/ffi/low_level_api/appendable_data.rs, line 928 at r2](https://reviewable.io:443/reviews/maidsafe/safe_core/337#-KRnzYfj4I-X_wZXYM4h:-KRnzYfj4I-X_wZXYM4i:b6c7bq7) ([raw file](https://github.com/maidsafe/safe_core/blob/565b467b1f58a615025dcf21fd0ed06fdaaa1d9c/src/ffi/low_level_api/appendable_data.rs#L928)):*
> ```Rust
> 
>             assert_eq!(filter_type, FilterType::WhiteList);
>             assert_eq!(appendable_data_insert_to_filter(ad_priv_h, sk2_h), 0);
> ```

Actually we kept the convention of `pk` being `PublicKey` and `sk` meaning `SecretKey` in crust and elsewhere in `safe_core` for conformance with `rust_sodium` and ultimately `libsodium` libraries we use. So `sk` here produced a minor confusion. Can you please call it `sign_key` or something else ? Also i noticed it got snucked in a few other places in existing test cases code. Could you pls run over and change those as well ?

---

*[src/ffi/low_level_api/appendable_data.rs, line 1016 at r2](https://reviewable.io:443/reviews/maidsafe/safe_core/337#-KRnxuQnWpokI52J7q-9:-KRnxuQnWpokI52J7q-A:b-n5o5qh) ([raw file](https://github.com/maidsafe/safe_core/blob/565b467b1f58a615025dcf21fd0ed06fdaaa1d9c/src/ffi/low_level_api/appendable_data.rs#L1016)):*
> ```Rust
>             assert_eq!(appendable_data_post(&app, ad_h, true), 0);
> 
>             assert_eq!(appendable_data_get(&app, ad_id_h, &mut ad_h), 0);
> ```

So if you are re-using `ad_h` for a fresh GET do release the previous object mapped to it - `assert_eq!(appendable_data_free(ad_h), 0)`. Although it's LRU with a fixed capacity and thus wont be a typical memory leak, it'll kind of demonstrate good practices.

Similarly check in other places if applicable.

---

*[src/ffi/low_level_api/appendable_data.rs, line 1050 at r2](https://reviewable.io:443/reviews/maidsafe/safe_core/337#-KRnyyz6gO5Md2kWDxcT:-KRnyyz6gO5Md2kWDxcU:b-rti45v) ([raw file](https://github.com/maidsafe/safe_core/blob/565b467b1f58a615025dcf21fd0ed06fdaaa1d9c/src/ffi/low_level_api/appendable_data.rs#L1050)):*
> ```Rust
> 
>     #[test]
>     fn sign_key() {
> ```

The test is wrongly named i think. It tests for the presence of encrypt key (`box_::Pk`) and not sign key (`sign::Pk`)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_core/337)*

**Comment by ustulation** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/ffi/low_level_api/appendable_data.rs, line 1123 at r3](https://reviewable.io:443/reviews/maidsafe/safe_core/337#-KS0mGxN6wuLfasawy5G:-KS0mGxN6wuLfasawy5H:b-vjcvno) ([raw file](https://github.com/maidsafe/safe_core/blob/421e46c2e533b133db12a93e08a7ef219dd6b2bf/src/ffi/low_level_api/appendable_data.rs#L1123)):*
> ```Rust
>     }
> 
>     fn reload_ad(app: &App, ad_id_h: DataIdHandle, ad_h: AppendableDataHandle) -> AppendableDataHandle {
> ```

1. This is over 100 char long line. It should have been formatted by rustfmt. Do configure your editor to apply rustfmt on save if you want to.
2. Since the function is named `reload`, may be better to take a `&mut ad_h` and free that and also collect into it ? So `let x = f(x);` will reduce to `f(&mut x);` - but only if you feel though - i'll leave this upto you.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_core/337)*

**Comment by ustulation** [comment]
Reviewed 2 of 3 files at r1, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_core/337)*

**Pull request merged**
