### PR TITLE
refactor/c_strings: Make use of UTF-8 non-null terminated strings

### PR DESCRIPTION
**Pull request by vinipsmaker**
This change is [Reviewable](https://reviewable.io/reviews/maidsafe/safe_core/321)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @krishnaIndia

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by ustulation** [comment]
Review status: 0 of 12 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/ffi/helper.rs, line 38 \[r1\]](https://reviewable.io:443/reviews/maidsafe/safe_core/321#-KQQkgby6NWAra12AXox:-KQQkgby6NWAra12AXoy:b-5smght) ([raw file](https://github.com/maidsafe/safe_core/blob/40a76705fdb947380d8c956b66f397eea7bc1cf0/src/ffi/helper.rs#L38)):*
> ```Rust
> pub unsafe fn c_utf8_to_string(ptr: *const u8, len: usize)
>                                -> Result<String, FfiError> {
>     String::from_utf8(slice::from_raw_parts(ptr, len).iter().cloned().collect())
> ```

instead of `.iter().clonec().collect()` you might be able to just use `to_owned()` to get the same effect.

---

*[src/ffi/helper.rs, line 48 \[r1\]](https://reviewable.io:443/reviews/maidsafe/safe_core/321#-KQQkvqvkBRYcAzPpp_m:-KQQkvqvkBRYcAzPpp_n:b-5smght) ([raw file](https://github.com/maidsafe/safe_core/blob/40a76705fdb947380d8c956b66f397eea7bc1cf0/src/ffi/helper.rs#L48)):*
> ```Rust
>     } else {
>         String::from_utf8(slice::from_raw_parts(ptr, len).iter().cloned()
>                           .collect())
> ```

instead of `.iter().clonec().collect()` you might be able to just use `to_owned()` to get the same effect.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_core/321)*

**Comment by dirvine** [comment]
Review status: 0 of 12 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/ffi/helper.rs, line 38 \[r1\]](https://reviewable.io:443/reviews/maidsafe/safe_core/321#-KQQkgby6NWAra12AXox:-KQQoiEr-xWhq2L6X8Wy:b-rqfvyx) ([raw file](https://github.com/maidsafe/safe_core/blob/40a76705fdb947380d8c956b66f397eea7bc1cf0/src/ffi/helper.rs#L38)):*
<details><summary><i>Previously, ustulation (Spandan Sharma) wrote…</i></summary>
> instead of `.iter().clonec().collect()` you might be able to just use `to_owned()` to get the same effect.
</details>
or `into_iter()` perhaps if we want a new collection.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_core/321)*

**Comment by vinipsmaker** [comment]
Review status: 0 of 12 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/ffi/helper.rs, line 38 \[r1\]](https://reviewable.io:443/reviews/maidsafe/safe_core/321#-KQQkgby6NWAra12AXox:-KQVPj3VnT6D7UzjvmqW:bq14gof) ([raw file](https://github.com/maidsafe/safe_core/blob/40a76705fdb947380d8c956b66f397eea7bc1cf0/src/ffi/helper.rs#L38)):*
<details><summary><i>Previously, dirvine (David Irvine) wrote…</i></summary>
> or `into_iter()` perhaps if we want a new collection.
</details>
Will do. Good spot.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_core/321)*

**Comment by ustulation** [comment]
Reviewed 6 of 12 files at r1, 6 of 6 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_core/321)*

**Pull request merged**
