### PR TITLE
(WIP) feat/appendable-data: add FFI API for appendable data

### PR DESCRIPTION
**Pull request by madadam**
This change is [Reviewable](https://reviewable.io/reviews/maidsafe/safe_core/323)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @ustulation

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by ustulation** [comment]
*[src/ffi/low_level_api/appendable_data.rs, line 132 \[r1\]](https://reviewable.io:443/reviews/maidsafe/safe_core/323#-KR4LwscqNMKAyONmhmy:-KR4LwscqNMKAyONmhmz:bjmaobl) ([raw file](https://github.com/maidsafe/safe_core/blob/216090a88834a66ebd8d41a7cf297b542fe04958/src/ffi/low_level_api/appendable_data.rs#L132)):*
> ```Rust
>                                                  -> i32 {
>     helper::catch_unwind_i32(|| {
>         let mut object_cache = unwrap!(object_cache().lock());
> ```

Mutex should not be held such early in the function and used much later. It should be moved way down where it's actually being used

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_core/323)*

**Comment by ustulation** [comment]
*[src/ffi/low_level_api/appendable_data.rs, line 165 \[r1\]](https://reviewable.io:443/reviews/maidsafe/safe_core/323#-KR4MBzaDLpJvIv9nV5l:-KR4MBzaDLpJvIv9nV5m:boraeit) ([raw file](https://github.com/maidsafe/safe_core/blob/216090a88834a66ebd8d41a7cf297b542fe04958/src/ffi/low_level_api/appendable_data.rs#L165)):*
> ```Rust
>                                                   -> i32 {
>     helper::catch_unwind_i32(|| {
>         let mut object_cache = unwrap!(object_cache().lock());
> ```

same as other - Lock mutex only when used.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_core/323)*

**Comment by ustulation** [comment]
*[src/ffi/low_level_api/appendable_data.rs, line 268 \[r1\]](https://reviewable.io:443/reviews/maidsafe/safe_core/323#-KR4UIdAA_qyJqI3SwHk:-KR4UIdAA_qyJqI3SwHl:b-y00ojt) ([raw file](https://github.com/maidsafe/safe_core/blob/216090a88834a66ebd8d41a7cf297b542fe04958/src/ffi/low_level_api/appendable_data.rs#L268)):*
> ```Rust
> /// Switch the filter of the appendable data to a whitelist.
> #[no_mangle]
> pub unsafe extern "C" fn appendable_data_switch_filter_to_whitelist(
> ```

function does not need to be unsafe

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_core/323)*

**Comment by ustulation** [comment]
Review status: 0 of 5 files reviewed at latest revision, 6 unresolved discussions.

---

*[src/ffi/low_level_api/appendable_data.rs, line 282 \[r1\]](https://reviewable.io:443/reviews/maidsafe/safe_core/323#-KR4UNozuAQ7lGtkdhgW:-KR4UNozuAQ7lGtkdhgX:b-y00ojt) ([raw file](https://github.com/maidsafe/safe_core/blob/216090a88834a66ebd8d41a7cf297b542fe04958/src/ffi/low_level_api/appendable_data.rs#L282)):*
> ```Rust
> /// Switch the filter of the appendable data to a blacklist.
> #[no_mangle]
> pub unsafe extern "C" fn appendable_data_switch_filter_to_blacklist(
> ```

function does not need to be unsafe

---

*[src/ffi/low_level_api/appendable_data.rs, line 297 \[r1\]](https://reviewable.io:443/reviews/maidsafe/safe_core/323#-KR4UTNNiF6ZiIMPw1BR:-KR4UTNNiF6ZiIMPw1BS:b-y00ojt) ([raw file](https://github.com/maidsafe/safe_core/blob/216090a88834a66ebd8d41a7cf297b542fe04958/src/ffi/low_level_api/appendable_data.rs#L297)):*
> ```Rust
> /// already present in the filter, this is a no-op.
> #[no_mangle]
> pub unsafe extern "C" fn appendable_data_insert_to_filter(appendable_data_h: AppendableDataHandle,
> ```

function does not need to be unsafe

---

*[src/ffi/low_level_api/appendable_data.rs, line 313 \[r1\]](https://reviewable.io:443/reviews/maidsafe/safe_core/323#-KR4UV1EG-3tEDENYE2J:-KR4UV1EG-3tEDENYE2K:b-y00ojt) ([raw file](https://github.com/maidsafe/safe_core/blob/216090a88834a66ebd8d41a7cf297b542fe04958/src/ffi/low_level_api/appendable_data.rs#L313)):*
> ```Rust
> /// isn't present in the filter, this is a no-op.
> #[no_mangle]
> pub unsafe extern "C" fn appendable_data_remove_from_filter(
> ```

function does not need to be unsafe

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_core/323)*

**Comment by ustulation** [comment]
merged in https://github.com/maidsafe/safe_core/pull/324

**Pull request closed without merging**
