### PR TITLE
RFC-0041: Low Level API - Part 0

### PR DESCRIPTION
**Pull request by ustulation**
Implement RFC 0041.
See Individual commits for details.

---
This change is [Reviewable](https://reviewable.io/reviews/maidsafe/safe_core/322)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @krishnaIndia

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by ustulation** [comment]
Reviewed 18 of 26 files at r1, 10 of 10 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_core/322)*

**Comment by madadam** [comment]
Reviewed 15 of 26 files at r1, 8 of 10 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[src/ffi/low_level_api/object_cache.rs, line 40 \[r2\]](https://reviewable.io:443/reviews/maidsafe/safe_core/322#-KR-Pm0vzFzDrQaJ-mY-:-KR-Pm0vzFzDrQaJ-mY0:bveazsk) ([raw file](https://github.com/maidsafe/safe_core/blob/62a3a8049211486227ceb5caaffe558da2e483da/src/ffi/low_level_api/object_cache.rs#L40)):*
> ```Rust
> 
>     unsafe {
>         ONCE.call_once(|| OBJECT_CACHE = Box::into_raw(Box::new(Default::default())));
> ```

Is OBJECT_CACHE ever dropped?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_core/322)*

**Comment by ustulation** [comment]
*[src/ffi/low_level_api/object_cache.rs, line 40 \[r2\]](https://reviewable.io:443/reviews/maidsafe/safe_core/322#-KR-Pm0vzFzDrQaJ-mY-:-KR-QHharEwp5pVDOZPJ:b-74i5dh) ([raw file](https://github.com/maidsafe/safe_core/blob/62a3a8049211486227ceb5caaffe558da2e483da/src/ffi/low_level_api/object_cache.rs#L40)):*
<details><summary><i>Previously, madadam (Adam Cigánek) wrote…</i></summary>
> Is OBJECT_CACHE ever dropped?
</details>
no - it's a singleton - you can reset it though

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_core/322)*

**Comment by ustulation** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/ffi/low_level_api/object_cache.rs, line 40 \[r2\]](https://reviewable.io:443/reviews/maidsafe/safe_core/322#-KR-Pm0vzFzDrQaJ-mY-:-KR-RuDDJtAetTmFjL7p:b-896fix) ([raw file](https://github.com/maidsafe/safe_core/blob/62a3a8049211486227ceb5caaffe558da2e483da/src/ffi/low_level_api/object_cache.rs#L40)):*
<details><summary><i>Previously, ustulation (Spandan Sharma) wrote…</i></summary>
> no - it's a singleton - you can reset it though
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_core/322)*

**Comment by madadam** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/ffi/low_level_api/object_cache.rs, line 40 \[r2\]](https://reviewable.io:443/reviews/maidsafe/safe_core/322#-KR-Pm0vzFzDrQaJ-mY-:-KR-TNGj3TVs3ZwvHBGz:b72ac7r) ([raw file](https://github.com/maidsafe/safe_core/blob/62a3a8049211486227ceb5caaffe558da2e483da/src/ffi/low_level_api/object_cache.rs#L40)):*
<details><summary><i>Previously, ustulation (Spandan Sharma) wrote…</i></summary>
> Done.
</details>
Then it's not going to be properly dropped on program exit, since we gave up ownership of it away from rust. Probably not really an issue in this case, unless some of the values in this struct do something special on drop, like join a thread or so. If they don't then it's probably fine. Better solution would be to use the lazy_static crate though.  

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_core/322)*

**Comment by ustulation** [comment]
*[src/ffi/low_level_api/object_cache.rs, line 40 \[r2\]](https://reviewable.io:443/reviews/maidsafe/safe_core/322#-KR-Pm0vzFzDrQaJ-mY-:-KR-RotuwZLY1JvX0ilN:b-96ddnc) ([raw file](https://github.com/maidsafe/safe_core/blob/62a3a8049211486227ceb5caaffe558da2e483da/src/ffi/low_level_api/object_cache.rs#L40)):*
<details><summary><i>Previously, madadam (Adam Cigánek) wrote…</i></summary>
> Then it's not going to be properly dropped on program exit, since we gave up ownership of it away from rust. Probably not really an issue in this case, unless some of the values in this struct do something special on drop, like join a thread or so. If they don't then it's probably fine. Better solution would be to use the lazy_static crate though.  
</details>
Its all lru cache of u64 vs objects .. nothing more .. singleton like this should be simple and sufficient for our case here

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_core/322)*

**Pull request merged**
