### PR TITLE
make safe_client example includes the messaging feature

### PR DESCRIPTION
**Pull request by maqi**
[Review on Reviewable](https://reviewable.io/reviews/maidsafe/safe_core/204)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @krishnaIndia

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by krishnaIndia** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[examples/safe_client.rs, line 122 \[r1\]](https://reviewable.io:443/reviews/maidsafe/safe_core/204#-KAJzTbMRbUiawgeXxxG:-KAJzTbMRbUiawgeXxxH:-28086295) ([raw file](https://github.com/maidsafe/safe_core/blob/7dd9b79bbedd124e4d5285f642d825a2fc546c7b/examples/safe_client.rs#L122)):*
Should this be an `or` condition? 

---

*[examples/safe_client.rs, line 139 \[r1\]](https://reviewable.io:443/reviews/maidsafe/safe_core/204#-KAJzY58uVIidtyiZtMY:-KAJzY58uVIidtyiZtMZ:-1003361570) ([raw file](https://github.com/maidsafe/safe_core/blob/7dd9b79bbedd124e4d5285f642d825a2fc546c7b/examples/safe_client.rs#L139)):*
The example the example hangs after the `memorable name` is entered? Am I missing something here?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/safe_core/204)*

**Comment by maqi** [comment]
*[examples/safe_client.rs, line 122 \[r1\]](https://reviewable.io:443/reviews/maidsafe/safe_core/204#-KAJzTbMRbUiawgeXxxG:-KAKDbliCh3VR5t3Oelb:1726584507) ([raw file](https://github.com/maidsafe/safe_core/blob/7dd9b79bbedd124e4d5285f642d825a2fc546c7b/examples/safe_client.rs#L122)):*
it is two "!=" used, so And condition is correct.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/safe_core/204)*

**Comment by maqi** [comment]
*[examples/safe_client.rs, line 139 \[r1\]](https://reviewable.io:443/reviews/maidsafe/safe_core/204#-KAJzY58uVIidtyiZtMY:-KAKDiA62KY4FejdxtkN:-45384053) ([raw file](https://github.com/maidsafe/safe_core/blob/7dd9b79bbedd124e4d5285f642d825a2fc546c7b/examples/safe_client.rs#L139)):*
it requires a vault network (having the messaging feature implemented) to give proper response. were you testing against a local network?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/safe_core/204)*

**Comment by maqi** [comment]
*[examples/safe_client.rs, line 122 \[r1\]](https://reviewable.io:443/reviews/maidsafe/safe_core/204#-KAJzTbMRbUiawgeXxxG:-KAKFdtNp3gZWuX6btU4:1502395188) ([raw file](https://github.com/maidsafe/safe_core/blob/7dd9b79bbedd124e4d5285f642d825a2fc546c7b/examples/safe_client.rs#L122)):*
pushed a new commit to use or condition

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/safe_core/204)*

**Comment by krishnaIndia** [comment]
*[examples/safe_client.rs, line 139 \[r1\]](https://reviewable.io:443/reviews/maidsafe/safe_core/204#-KAJzY58uVIidtyiZtMY:-KAKG4fbYPdJ6UleL_-O:-985667130) ([raw file](https://github.com/maidsafe/safe_core/blob/7dd9b79bbedd124e4d5285f642d825a2fc546c7b/examples/safe_client.rs#L139)):*
My bad, used mock network to test.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/safe_core/204)*

**Comment by krishnaIndia** [comment]
*[examples/safe_client.rs, line 139 \[r1\]](https://reviewable.io:443/reviews/maidsafe/safe_core/204#-KAJzY58uVIidtyiZtMY:-KAKIVGMQrvMlqMWXHnl:-86549440) ([raw file](https://github.com/maidsafe/safe_core/blob/7dd9b79bbedd124e4d5285f642d825a2fc546c7b/examples/safe_client.rs#L139)):*
Can we add a `if` condition to check if the example is run against a mock network and show a proper message?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/safe_core/204)*

**Comment by krishnaIndia** [comment]
There is merge conflict, the PR needs to be updated after resolving the conflicts.

**Comment by maqi** [comment]
*[examples/safe_client.rs, line 139 \[r1\]](https://reviewable.io:443/reviews/maidsafe/safe_core/204#-KAJzY58uVIidtyiZtMY:-KAKSOUcosTEbtIi0Ti0:625243379) ([raw file](https://github.com/maidsafe/safe_core/blob/7dd9b79bbedd124e4d5285f642d825a2fc546c7b/examples/safe_client.rs#L139)):*
probably not. the compiler complains:
: attributes on non-item statements and expressions are experimental. (see issue #15701)
examples/safe_client.rs:117 #[cfg(feature = "use-mock-routing")]

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/safe_core/204)*

**Comment by krishnaIndia** [comment]
*[examples/safe_client.rs, line 139 \[r1\]](https://reviewable.io:443/reviews/maidsafe/safe_core/204#-KAJzY58uVIidtyiZtMY:-KAKUB-Nblw2Vx6IOWgg:803352775) ([raw file](https://github.com/maidsafe/safe_core/blob/7dd9b79bbedd124e4d5285f642d825a2fc546c7b/examples/safe_client.rs#L139)):*
After the use statements if define a boolean variable
```
#[cfg(feature = "use-mock-routing")]
const MOCK_NETWORK: bool = true;
#[cfg(not(feature = "use-mock-routing"))]
const MOCK_NETWORK: bool = false;
```

Then we will be able to use that to validate. Is this possible?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/safe_core/204)*

**Comment by krishnaIndia** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/safe_core/204)*

**Pull request merged**
