### PR TITLE
Migrate to Routing 0.13.0.

### PR DESCRIPTION
**Pull request by afck**
And update other dependencies.

---
This change is [Reviewable](https://reviewable.io/reviews/maidsafe/safe_core/236)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @krishnaIndia

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by ustulation** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_core/236)*

**Pull request merged**
