### PR TITLE
couple of changes to complete the testing of messaging feature

### PR DESCRIPTION
**Pull request by maqi**
[Review on Reviewable](https://reviewable.io/reviews/maidsafe/safe_core/206)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @krishnaIndia

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by krishnaIndia** [comment]
Thanks @maqi Will review and get it merged today

**Comment by krishnaIndia** [comment]
The PR depends on the WIP routing code. Until that gets published, merging this doesn't make sense. Marking it as WIP until then.

**Comment by maqi** [comment]
The routing v0.7.0 has now been published, and the vault master header now get PR https://github.com/maidsafe/safe_vault/pull/332 merged in (which contains the code of features that required by this PR's example code).
So this PR shall now be merged to demo such messaging features.

**Comment by krishnaIndia** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/safe_core/206)*

**Comment by ustulation** [comment]
r? @maqi 
This must be redone in light of recent changes

**Comment by maqi** [comment]
seems messaging is not required as part of the MVP, so the update may be postponed after the MVP.

**Comment by ustulation** [comment]
@maqi - should i close this (you can if you want to) or do you want it remain opened ?

**Comment by maqi** [comment]
closing this PR as the messaging may get refactored in near future.

**Pull request closed without merging**
