### PR TITLE
feat/stats: expose number GETs/PUTs/POSTs/DELETEs

### PR DESCRIPTION
**Pull request by vinipsmaker**
We get stats of every attempt, not only the successful ones.

---
This change is [Reviewable](https://reviewable.io/reviews/maidsafe/safe_core/265)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
Thanks for the pull request, and welcome! The MaidSafe team is excited to review your changes, and you should hear from @krishnaIndia (or someone else) soon.

If any changes to this PR are deemed necessary, please add them as extra commits. This ensures that the reviewer can see what has changed since they last reviewed the code. The way GitHub handles out-of-date commits, this should also make it reasonably obvious what issues have or haven't been addressed. Large or tricky changes may require several passes of review and changes.

Please see [CONTRIBUTOR.md](../blob/master/CONTRIBUTOR) for more information.

**Comment by ustulation** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/ffi/mod.rs, line 362 \[r3\]](https://reviewable.io:443/reviews/maidsafe/safe_core/265#-KKxnzlP4LRZ6Y9O8uNE:-KKxnzlP4LRZ6Y9O8uNF:1636975786) ([raw file](https://github.com/maidsafe/safe_core/blob/dd96a729c43331dda67db9fc67484c8398c0d8c0/src/ffi/mod.rs#L362)):*
> ```Rust
> #[no_mangle]
> #[allow(unsafe_code)]
> /// Return the amount of calls that were done to `get`
> ```

just to be in sync with other functions, can you pls move the documentation above the code part (`#[no_mangle]`) ? Also same for the rest of the new functions added below

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_core/265)*

**Comment by ustulation** [comment]
Reviewed 5 of 6 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_core/265)*

**Pull request merged**
