### PR TITLE
fix/dns: enable registered client to fetch public dns file

### PR DESCRIPTION
**Pull request by krishnaIndia**
Previously only registered owner and unregistered client could fetch the public dns file. A registered client could not fetch a public file that had been created by another owner. This fix aims to resolve that issue.

---
This change is [Reviewable](https://reviewable.io/reviews/maidsafe/safe_core/263)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @ustulation

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by ustulation** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/dns/dns_operations/mod.rs, line 178 \[r1\]](https://reviewable.io:443/reviews/maidsafe/safe_core/263#-KKiSQUIE5ERs3xlD-1a:-KKiSQUIE5ERs3xlD-1b:2088528739) ([raw file](https://github.com/maidsafe/safe_core/blob/faca936608bc293e49a5e04e89500a05ca6e8e38/src/dns/dns_operations/mod.rs#L178)):*
> ```Rust
>             Ok(_) => (),
>             Err(DnsError::CoreError(CoreError::OperationForbiddenForClient)) => (),
>             Err(DnsError::NfsError(NfsError::CoreError(CoreError::OperationForbiddenForClient))) => {
> ```

this is refactored without functional change and is `>100` characters long. maybe because of some rustfmt.toml messing things somewhere ? pls set your rustfmt to default (80 characters ideal and 100 max)

---

*[src/dns/dns_operations/mod.rs, line 203 \[r1\]](https://reviewable.io:443/reviews/maidsafe/safe_core/263#-KKiRng3EPKXKcXXEmBy:-KKiRng3EPKXKcXXEmBz:2088528739) ([raw file](https://github.com/maidsafe/safe_core/blob/faca936608bc293e49a5e04e89500a05ca6e8e38/src/dns/dns_operations/mod.rs#L203)):*
> ```Rust
>             Err(DnsError::CoreError(CoreError::OperationForbiddenForClient)) => (),
>             Err(DnsError::NfsError(NfsError::CoreError(CoreError::OperationForbiddenForClient))) => {
>                 ()
> ```

this is refactored without functional change and is `>100` characters long. maybe because of some rustfmt.toml messing things somewhere ? pls set your rustfmt to default (80 characters ideal and 100 max)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_core/263)*

**Comment by krishnaIndia** [comment]
*[src/dns/dns_operations/mod.rs, line 178 \[r1\]](https://reviewable.io:443/reviews/maidsafe/safe_core/263#-KKiSQUIE5ERs3xlD-1a:-KKqYXXe3-Ij4w-6ndpQ:-499146009) ([raw file](https://github.com/maidsafe/safe_core/blob/faca936608bc293e49a5e04e89500a05ca6e8e38/src/dns/dns_operations/mod.rs#L178)):*
<details><summary><i>Previously, ustulation (Spandan Sharma) wrote…</i></summary>
> this is refactored without functional change and is `>100` characters long. maybe because of some rustfmt.toml messing things somewhere ? pls set your rustfmt to default (80 characters ideal and 100 max)
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_core/263)*

**Comment by krishnaIndia** [comment]
*[src/dns/dns_operations/mod.rs, line 203 \[r1\]](https://reviewable.io:443/reviews/maidsafe/safe_core/263#-KKiRng3EPKXKcXXEmBy:-KKqYZc5YrtWqvl9ZO60:-499146009) ([raw file](https://github.com/maidsafe/safe_core/blob/faca936608bc293e49a5e04e89500a05ca6e8e38/src/dns/dns_operations/mod.rs#L203)):*
<details><summary><i>Previously, ustulation (Spandan Sharma) wrote…</i></summary>
> this is refactored without functional change and is `>100` characters long. maybe because of some rustfmt.toml messing things somewhere ? pls set your rustfmt to default (80 characters ideal and 100 max)
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_core/263)*

**Comment by ustulation** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/safe_core/263)*

**Pull request merged**
