### PR TITLE
modified some files to silence lints

### PR DESCRIPTION
**Pull request by waynenilsen**
i also added the dot graph for deps

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
Thanks for the pull request, and welcome! The MaidSafe team is excited to review your changes, and you should hear from @ustulation (or someone else) soon.

If any changes to this PR are deemed necessary, please add them as extra commits. This ensures that the reviewer can see what has changed since they last reviewed the code. The way GitHub handles out-of-date commits, this should also make it reasonably obvious what issues have or haven't been addressed. Large or tricky changes may require several passes of review and changes.

Please see [CONTRIBUTOR.md](../blob/master/CONTRIBUTOR) for more information.

**Comment by ustulation** [comment]
1) usage of `#[allow(unused)]` is prohibited. If there are lint warnings related to it, it means that there is something private to this crate and not used within the crate - so it's pretty useless and we should delete it. The lint will not complain about unused constructs if they are visible to interfacing crates.
2) some changes are already incorporated it seems
3) The routing API has changed and thus there is a refactor in safe_core so if there is still anything in this PR that would be missing in the current master after https://github.com/maidsafe/safe_core/pull/194 is merged, then it would be useful to get a new/fresh PR.

Closing this.

**Comment by waynenilsen** [comment]
This was part of a series of PRs that I made a while back to try to build safe_vault. I made several forks to get all deps to build and finally got safe_vault to build. I made a bunch of PRs as a matter of courtesy. The *only* purpose of this PR was to get the crate to build, which it does now without it.

I understand why this was closed. Thanks for the comments.

**Comment by dirvine** [comment]
No worries Wayn, thank you and keep PR'ing us. It's all good :+1:

**Pull request closed without merging**
